# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/liux/Work/DOCTORS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/liux/Work/DOCTORS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liux/Work/DOCTORS/CMakeFiles /home/liux/Work/DOCTORS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liux/Work/DOCTORS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/liux/Work/DOCTORS/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DOCTORS

# Build rule for target.
DOCTORS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DOCTORS
.PHONY : DOCTORS

# fast build rule for target.
DOCTORS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/build
.PHONY : DOCTORS/fast

src/ctdatamanager.o: src/ctdatamanager.cpp.o
.PHONY : src/ctdatamanager.o

# target to build an object file
src/ctdatamanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/ctdatamanager.cpp.o
.PHONY : src/ctdatamanager.cpp.o

src/ctdatamanager.i: src/ctdatamanager.cpp.i
.PHONY : src/ctdatamanager.i

# target to preprocess a source file
src/ctdatamanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/ctdatamanager.cpp.i
.PHONY : src/ctdatamanager.cpp.i

src/ctdatamanager.s: src/ctdatamanager.cpp.s
.PHONY : src/ctdatamanager.s

# target to generate assembly for a file
src/ctdatamanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/ctdatamanager.cpp.s
.PHONY : src/ctdatamanager.cpp.s

src/device_utils.o: src/device_utils.cu.o
.PHONY : src/device_utils.o

# target to build an object file
src/device_utils.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/device_utils.cu.o
.PHONY : src/device_utils.cu.o

src/device_utils.i: src/device_utils.cu.i
.PHONY : src/device_utils.i

# target to preprocess a source file
src/device_utils.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/device_utils.cu.i
.PHONY : src/device_utils.cu.i

src/device_utils.s: src/device_utils.cu.s
.PHONY : src/device_utils.s

# target to generate assembly for a file
src/device_utils.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/device_utils.cu.s
.PHONY : src/device_utils.cu.s

src/dtfrparser.o: src/dtfrparser.cpp.o
.PHONY : src/dtfrparser.o

# target to build an object file
src/dtfrparser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/dtfrparser.cpp.o
.PHONY : src/dtfrparser.cpp.o

src/dtfrparser.i: src/dtfrparser.cpp.i
.PHONY : src/dtfrparser.i

# target to preprocess a source file
src/dtfrparser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/dtfrparser.cpp.i
.PHONY : src/dtfrparser.cpp.i

src/dtfrparser.s: src/dtfrparser.cpp.s
.PHONY : src/dtfrparser.s

# target to generate assembly for a file
src/dtfrparser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/dtfrparser.cpp.s
.PHONY : src/dtfrparser.cpp.s

src/histogram.o: src/histogram.cpp.o
.PHONY : src/histogram.o

# target to build an object file
src/histogram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/histogram.cpp.o
.PHONY : src/histogram.cpp.o

src/histogram.i: src/histogram.cpp.i
.PHONY : src/histogram.i

# target to preprocess a source file
src/histogram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/histogram.cpp.i
.PHONY : src/histogram.cpp.i

src/histogram.s: src/histogram.cpp.s
.PHONY : src/histogram.s

# target to generate assembly for a file
src/histogram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/histogram.cpp.s
.PHONY : src/histogram.cpp.s

src/legendre.o: src/legendre.cpp.o
.PHONY : src/legendre.o

# target to build an object file
src/legendre.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/legendre.cpp.o
.PHONY : src/legendre.cpp.o

src/legendre.i: src/legendre.cpp.i
.PHONY : src/legendre.i

# target to preprocess a source file
src/legendre.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/legendre.cpp.i
.PHONY : src/legendre.cpp.i

src/legendre.s: src/legendre.cpp.s
.PHONY : src/legendre.s

# target to generate assembly for a file
src/legendre.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/legendre.cpp.s
.PHONY : src/legendre.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/materialutils.o: src/materialutils.cpp.o
.PHONY : src/materialutils.o

# target to build an object file
src/materialutils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/materialutils.cpp.o
.PHONY : src/materialutils.cpp.o

src/materialutils.i: src/materialutils.cpp.i
.PHONY : src/materialutils.i

# target to preprocess a source file
src/materialutils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/materialutils.cpp.i
.PHONY : src/materialutils.cpp.i

src/materialutils.s: src/materialutils.cpp.s
.PHONY : src/materialutils.s

# target to generate assembly for a file
src/materialutils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/materialutils.cpp.s
.PHONY : src/materialutils.cpp.s

src/mcnpwriter.o: src/mcnpwriter.cpp.o
.PHONY : src/mcnpwriter.o

# target to build an object file
src/mcnpwriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/mcnpwriter.cpp.o
.PHONY : src/mcnpwriter.cpp.o

src/mcnpwriter.i: src/mcnpwriter.cpp.i
.PHONY : src/mcnpwriter.i

# target to preprocess a source file
src/mcnpwriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/mcnpwriter.cpp.i
.PHONY : src/mcnpwriter.cpp.i

src/mcnpwriter.s: src/mcnpwriter.cpp.s
.PHONY : src/mcnpwriter.s

# target to generate assembly for a file
src/mcnpwriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/mcnpwriter.cpp.s
.PHONY : src/mcnpwriter.cpp.s

src/mesh.o: src/mesh.cpp.o
.PHONY : src/mesh.o

# target to build an object file
src/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/mesh.cpp.o
.PHONY : src/mesh.cpp.o

src/mesh.i: src/mesh.cpp.i
.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s
.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/nuclidedata.o: src/nuclidedata.cpp.o
.PHONY : src/nuclidedata.o

# target to build an object file
src/nuclidedata.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/nuclidedata.cpp.o
.PHONY : src/nuclidedata.cpp.o

src/nuclidedata.i: src/nuclidedata.cpp.i
.PHONY : src/nuclidedata.i

# target to preprocess a source file
src/nuclidedata.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/nuclidedata.cpp.i
.PHONY : src/nuclidedata.cpp.i

src/nuclidedata.s: src/nuclidedata.cpp.s
.PHONY : src/nuclidedata.s

# target to generate assembly for a file
src/nuclidedata.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/nuclidedata.cpp.s
.PHONY : src/nuclidedata.cpp.s

src/outwriter.o: src/outwriter.cpp.o
.PHONY : src/outwriter.o

# target to build an object file
src/outwriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/outwriter.cpp.o
.PHONY : src/outwriter.cpp.o

src/outwriter.i: src/outwriter.cpp.i
.PHONY : src/outwriter.i

# target to preprocess a source file
src/outwriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/outwriter.cpp.i
.PHONY : src/outwriter.cpp.i

src/outwriter.s: src/outwriter.cpp.s
.PHONY : src/outwriter.s

# target to generate assembly for a file
src/outwriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/outwriter.cpp.s
.PHONY : src/outwriter.cpp.s

src/quadrature.o: src/quadrature.cpp.o
.PHONY : src/quadrature.o

# target to build an object file
src/quadrature.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/quadrature.cpp.o
.PHONY : src/quadrature.cpp.o

src/quadrature.i: src/quadrature.cpp.i
.PHONY : src/quadrature.i

# target to preprocess a source file
src/quadrature.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/quadrature.cpp.i
.PHONY : src/quadrature.cpp.i

src/quadrature.s: src/quadrature.cpp.s
.PHONY : src/quadrature.s

# target to generate assembly for a file
src/quadrature.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/quadrature.cpp.s
.PHONY : src/quadrature.cpp.s

src/solver.o: src/solver.cpp.o
.PHONY : src/solver.o

# target to build an object file
src/solver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/solver.cpp.o
.PHONY : src/solver.cpp.o

src/solver.i: src/solver.cpp.i
.PHONY : src/solver.i

# target to preprocess a source file
src/solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/solver.cpp.i
.PHONY : src/solver.cpp.i

src/solver.s: src/solver.cpp.s
.PHONY : src/solver.s

# target to generate assembly for a file
src/solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/solver.cpp.s
.PHONY : src/solver.cpp.s

src/solver_gpu.o: src/solver_gpu.cu.o
.PHONY : src/solver_gpu.o

# target to build an object file
src/solver_gpu.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/solver_gpu.cu.o
.PHONY : src/solver_gpu.cu.o

src/solver_gpu.i: src/solver_gpu.cu.i
.PHONY : src/solver_gpu.i

# target to preprocess a source file
src/solver_gpu.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/solver_gpu.cu.i
.PHONY : src/solver_gpu.cu.i

src/solver_gpu.s: src/solver_gpu.cu.s
.PHONY : src/solver_gpu.s

# target to generate assembly for a file
src/solver_gpu.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/solver_gpu.cu.s
.PHONY : src/solver_gpu.cu.s

src/solver_metadata_extract.o: src/solver_metadata_extract.cpp.o
.PHONY : src/solver_metadata_extract.o

# target to build an object file
src/solver_metadata_extract.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/solver_metadata_extract.cpp.o
.PHONY : src/solver_metadata_extract.cpp.o

src/solver_metadata_extract.i: src/solver_metadata_extract.cpp.i
.PHONY : src/solver_metadata_extract.i

# target to preprocess a source file
src/solver_metadata_extract.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/solver_metadata_extract.cpp.i
.PHONY : src/solver_metadata_extract.cpp.i

src/solver_metadata_extract.s: src/solver_metadata_extract.cpp.s
.PHONY : src/solver_metadata_extract.s

# target to generate assembly for a file
src/solver_metadata_extract.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/solver_metadata_extract.cpp.s
.PHONY : src/solver_metadata_extract.cpp.s

src/sourceparams.o: src/sourceparams.cpp.o
.PHONY : src/sourceparams.o

# target to build an object file
src/sourceparams.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/sourceparams.cpp.o
.PHONY : src/sourceparams.cpp.o

src/sourceparams.i: src/sourceparams.cpp.i
.PHONY : src/sourceparams.i

# target to preprocess a source file
src/sourceparams.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/sourceparams.cpp.i
.PHONY : src/sourceparams.cpp.i

src/sourceparams.s: src/sourceparams.cpp.s
.PHONY : src/sourceparams.s

# target to generate assembly for a file
src/sourceparams.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/sourceparams.cpp.s
.PHONY : src/sourceparams.cpp.s

src/sweep.o: src/sweep.cpp.o
.PHONY : src/sweep.o

# target to build an object file
src/sweep.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/sweep.cpp.o
.PHONY : src/sweep.cpp.o

src/sweep.i: src/sweep.cpp.i
.PHONY : src/sweep.i

# target to preprocess a source file
src/sweep.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/sweep.cpp.i
.PHONY : src/sweep.cpp.i

src/sweep.s: src/sweep.cpp.s
.PHONY : src/sweep.s

# target to generate assembly for a file
src/sweep.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/sweep.cpp.s
.PHONY : src/sweep.cpp.s

src/xsection.o: src/xsection.cpp.o
.PHONY : src/xsection.o

# target to build an object file
src/xsection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/xsection.cpp.o
.PHONY : src/xsection.cpp.o

src/xsection.i: src/xsection.cpp.i
.PHONY : src/xsection.i

# target to preprocess a source file
src/xsection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/xsection.cpp.i
.PHONY : src/xsection.cpp.i

src/xsection.s: src/xsection.cpp.s
.PHONY : src/xsection.s

# target to generate assembly for a file
src/xsection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DOCTORS.dir/build.make CMakeFiles/DOCTORS.dir/src/xsection.cpp.s
.PHONY : src/xsection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DOCTORS"
	@echo "... src/ctdatamanager.o"
	@echo "... src/ctdatamanager.i"
	@echo "... src/ctdatamanager.s"
	@echo "... src/device_utils.o"
	@echo "... src/device_utils.i"
	@echo "... src/device_utils.s"
	@echo "... src/dtfrparser.o"
	@echo "... src/dtfrparser.i"
	@echo "... src/dtfrparser.s"
	@echo "... src/histogram.o"
	@echo "... src/histogram.i"
	@echo "... src/histogram.s"
	@echo "... src/legendre.o"
	@echo "... src/legendre.i"
	@echo "... src/legendre.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/materialutils.o"
	@echo "... src/materialutils.i"
	@echo "... src/materialutils.s"
	@echo "... src/mcnpwriter.o"
	@echo "... src/mcnpwriter.i"
	@echo "... src/mcnpwriter.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/nuclidedata.o"
	@echo "... src/nuclidedata.i"
	@echo "... src/nuclidedata.s"
	@echo "... src/outwriter.o"
	@echo "... src/outwriter.i"
	@echo "... src/outwriter.s"
	@echo "... src/quadrature.o"
	@echo "... src/quadrature.i"
	@echo "... src/quadrature.s"
	@echo "... src/solver.o"
	@echo "... src/solver.i"
	@echo "... src/solver.s"
	@echo "... src/solver_gpu.o"
	@echo "... src/solver_gpu.i"
	@echo "... src/solver_gpu.s"
	@echo "... src/solver_metadata_extract.o"
	@echo "... src/solver_metadata_extract.i"
	@echo "... src/solver_metadata_extract.s"
	@echo "... src/sourceparams.o"
	@echo "... src/sourceparams.i"
	@echo "... src/sourceparams.s"
	@echo "... src/sweep.o"
	@echo "... src/sweep.i"
	@echo "... src/sweep.s"
	@echo "... src/xsection.o"
	@echo "... src/xsection.i"
	@echo "... src/xsection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/liux/Work/DOCTORS/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

